import type { ClaimData } from '@/types/claim';
import type { SurveyorProfile } from '@/types/vehicle';

export const MOCK_PROFILE: SurveyorProfile = {
  name: 'Rajesh Kumar Sharma',
  qualifications: 'B.E. (Mech.), AIII',
  licenceNumber: 'SUR/MH/2019/004521',
  licenceExpiry: '2027-03-31',
  iiislaNumber: 'IIISLA-MH-04521',
  code: 'SUR-MH-4521',
  categories: 'Motor Vehicles',
  mobile: '9876543210',
  city: 'Pune',
  state: 'Maharashtra',
  email: 'rajesh.sharma@surveyos.in',
  address: '301, Shivaji Nagar, Pune – 411005',
  gstNumber: '27AAAPS1234A1Z5',
  bankName: 'State Bank of India',
  bankAccount: '32145678901',
  bankIFSC: 'SBIN0001234',
  panNumber: 'AAAPS1234A',
  aiProvider: 'gemini',
  geminiApiKeys: [],
  groqApiKeys: [],
  nvidiaApiKeys: [],
  geminiApiKey: '',
  groqApiKey: '',
  googleClientId: '',
  surveyorId: 'SUS-1042',
  subscriptionStatus: 'active',
  subscriptionExpiry: '2027-03-31',
  isAdmin: false,
  trialStartDate: null,
  trialEndDate: null,
  lastPaymentDate: '2026-06-01',
  referralCode: 'SUS-RAJESH',
  referredBy: null,
  referralCount: 0,
  referralBonusDays: 0,
  signatureDataUrl: null,
  stampDataUrl: null,
  accessRequestSubmitted: false,
  irdaiLicence: 'SUR/MH/2019/004521',
};

export const MOCK_CLAIM: ClaimData = {
  id: 'claim-demo-001',
  createdAt: '2026-06-10T09:30:00.000Z',
  updatedAt: '2026-06-10T14:20:00.000Z',
  surveyType: 'final',
  vehicleType: 'private',
  depreciationType: 'standard',
  isSpotCompleted: true,
  isCompleted: false,
  isActive: true,
  reportNo: 'UIIC/SPOT/2026/MH-1042',
  reportDate: '2026-06-10',

  vehicle: {
    registrationNumber: 'MH-12-AB-4567',
    make: 'Maruti Suzuki',
    model: 'Swift ZXi',
    yearOfManufacture: 2021,
    chassisNumber: 'MA3FJEB1S00123456',
    engineNumber: 'K12N3456789',
    cubicCapacity: '1197 cc',
    colour: 'Pearl Arctic White',
    bodyType: 'Hatchback',
    classOfVehicle: 'LMV (Motor Car)',
    fuel: 'Petrol',
    dateOfRegistration: '2021-04-15',
    hypothecation: 'HDFC Bank Ltd., Pune',
    fitnessNo: '',
    fitnessValidUpto: '',
    route: '',
    grossWeight: null,
    unladenWeight: null,
    registeredLoadWeight: '',
    actualPayload: '',
    odometer: '28,456 km',
    preAccidentCondition: 'Good',
    registrationType: 'Permanent',
    registeringAuthority: 'RTO Pune (MH-12)',
    registrationValidUpTo: '',
    rcEndorsement: 'HDFC Bank Ltd.',
    seatingCapacity: '5',
    passengersAtAccident: '',
    passengerType: '',
    goodsWeightAtAccident: '',
    natureOfGoods: '',
    fitnessType: 'NORMAL',
    isCommercial: false,
    passengersContravention: '',
    loadChallanNumber: '',
    loadChallanDate: '',
    detailsOfGoodsCarried: '',
  },

  driver: {
    name: 'Suresh Mohan Patil',
    parentName: 'Mohan Patil',
    relationType: 'S/o',
    licenceType: 'LMV',
    licenceNumber: 'MH1220140056789',
    dateOfBirth: '1985-07-22',
    dateOfIssue: '2014-03-10',
    address: '45, Deccan Gymkhana, Pune – 411004',
    issuingAuthority: 'RTO Pune',
    vehicleClasses: 'LMV',
    validityNonTransport: '2034-03-09',
    validityTransport: '',
    verificationStatus: 'verified',
    invalidRemarks: '',
    badgeNumber: '',
    authorisedToDrive: 'Yes – LMV',
    verificationDate: '2026-06-10',
  },

  policy: {
    policyNumber: 'UIIC/PUN/OD/2025-26/012345',
    claimNumber: 'UIIC/PUN/CLM/2026/009876',
    insurerName: 'United India Insurance Co. Ltd.',
    insuredName: 'Suresh Mohan Patil',
    insuredAddress: '45, Deccan Gymkhana, Pune – 411004',
    insuredMobile: '9812345678',
    idv: '6,50,000',
    policyType: 'Comprehensive',
    periodFrom: '2025-04-01',
    periodTo: '2026-03-31',
    policyIssuingOffice: 'UIIC Divisional Office, Pune',
    appointingOffice: 'UIIC D.O., Shivajinagar, Pune – 411005',
    hpaWith: 'HDFC Bank Ltd., Pune',
  },

  accident: {
    dateAndTime: '2026-06-08T17:30:00',
    placeOfAccident: 'Baner Road, Near Balewadi, Pune – 411045',
    causeOfAccident: 'Dashed against divider / loss of control on a slippery road surface',
    dateOfSurvey: '2026-06-10',
    placeOfSurvey: 'Shree Motors Workshop, Baner, Pune',
    policeStation: 'Chatushrungi Police Station',
    firNumber: 'FIR/CHT/2026/0447',
    firDate: '2026-06-08',
    fireBrigadeReportNo: '',
    pincode: '411045',
    locationCode: '',
    appointmentDate: '2026-06-09',
    workshopName: 'Shree Motors (MSIL Authorised)',
    workshopAddress: 'Plot No. 7, Baner-Pashan Link Road, Pune – 411021',
    workshopPhone: '020-27294567',
    workshopFax: '020-27294568',
    workshopEmail: 'shreeMotors@example.com',
    remarks: 'Vehicle was inspected at the workshop. Damage is consistent with the nature and direction of the reported accident.',
    thirdPartyDetails: '',
  },

  assessmentRows: [
    { id: 'r1', srNo: 1, particulars: 'Front Bumper Assembly', partType: 'plastic', gst: 28, section: 'parts', allowed: true, estimated: 8500, assessed: 7800, action: 'replace', remarks: '' },
    { id: 'r2', srNo: 2, particulars: 'Bonnet Assembly', partType: 'metal', gst: 28, section: 'parts', allowed: true, estimated: 18000, assessed: 15500, action: 'replace', remarks: '' },
    { id: 'r3', srNo: 3, particulars: 'R/H Front Fender', partType: 'metal', gst: 28, section: 'parts', allowed: true, estimated: 9800, assessed: 8600, action: 'replace', remarks: '' },
    { id: 'r4', srNo: 4, particulars: 'R/H Head Lamp Assembly', partType: 'glass', gst: 18, section: 'parts', allowed: true, estimated: 12500, assessed: 11000, action: 'replace', remarks: '' },
    { id: 'r5', srNo: 5, particulars: 'Windscreen Glass (Front)', partType: 'glass', gst: 18, section: 'parts', allowed: true, estimated: 9200, assessed: 9200, action: 'replace', remarks: '' },
    { id: 'r6', srNo: 6, particulars: 'R/H Side ORVM', partType: 'plastic', gst: 28, section: 'parts', allowed: true, estimated: 3800, assessed: 3500, action: 'replace', remarks: '' },
    { id: 'r7', srNo: 7, particulars: 'Front Grille Assembly', partType: 'plastic', gst: 28, section: 'parts', allowed: true, estimated: 2400, assessed: 2200, action: 'replace', remarks: '' },
    { id: 'r8', srNo: 8, particulars: 'Radiator Grille Support', partType: 'plastic', gst: 28, section: 'parts', allowed: true, estimated: 1800, assessed: 1600, action: 'replace', remarks: '' },
    { id: 'r9', srNo: 9, particulars: 'Panel Beating & Denting – Bonnet, Fender', partType: 'labour', gst: 18, section: 'labour', allowed: true, estimated: 5500, assessed: 5000, action: 'repair', remarks: '' },
    { id: 'r10', srNo: 10, particulars: 'Painting – Bonnet, Front Fender, Door', partType: 'paint', gst: 18, section: 'paint', allowed: true, estimated: 12000, assessed: 10500, action: 'repair', remarks: '' },
    { id: 'r11', srNo: 11, particulars: 'Spoiler – Front (claimed, not damaged)', partType: 'plastic', gst: 28, section: 'parts', allowed: false, estimated: 4500, assessed: 0, action: 'disallow', remarks: 'Not related to the accident' },
  ],

  spotDetails: {
    reportNo: 'UIIC/SPOT/2026/MH-1042',
    reportDate: '2026-06-08',
    allotmentDate: '2026-06-08',
    surveyDatetime: '2026-06-08T19:15:00',
    tpInvolved: 'no',
    policeReported: 'yes',
    panchanama: 'no',
    damageSeverity: 'moderate',
    airbags: 'deployed',
    drivable: 'no',
    comments: 'Vehicle brought in by crane to workshop. Both airbags deployed. Front end damage significant.',
    repairs: 'Front bumper, bonnet, R/H fender, headlamp, windscreen to be replaced. Panel beating & painting required.',
    enclosures: 'RC copy, DL copy, Insurance copy, Photographs',
    permitNo: '',
    permitType: '',
    permitFrom: '',
    permitTo: '',
    natureOfPermit: '',
    areaOfOperation: '',
    fitnessType: '',
    authNo: '',
    authValid: '',
    verificationFlags: { rc: 'Verified', dl: 'Verified', permit: 'N/A', fitness: 'N/A', loadChallan: 'N/A', fireReport: 'N/A', fir: 'FIR obtained' },
    gvw: null,
    ulw: null,
    loadCapacity: null,
    actualLoad: null,
    flagOverload: false,
    challanNo: '',
    challanDate: '',
    loadDesc: '',
    loadOrigin: '',
    loadDest: '',
    repairWorkshop: 'Shree Motors, Baner, Pune',
  },

  spotDamageRows: [
    { id: 'sd1', component: 'Front Bumper', damage: 'Broken, cracked' },
    { id: 'sd2', component: 'Bonnet Assembly', damage: 'Dented, crumpled' },
    { id: 'sd3', component: 'R/H Front Fender', damage: 'Dented, bent' },
    { id: 'sd4', component: 'R/H Headlamp', damage: 'Cracked, broken' },
    { id: 'sd5', component: 'Windscreen (Front)', damage: 'Star crack, spreading' },
    { id: 'sd6', component: 'R/H ORVM', damage: 'Broken' },
  ],

  reinspection: {
    refNo: '',
    date: '',
    surveyRef: '',
    surveyDate: '',
    repairQuality: 'satisfactory',
    vehicleCondition: 'roadworthy',
    salvageStatus: 'na',
    observations: '',
    riAppointmentDate: '',
    repairsAsAssessed: 'YES',
    repairAuthDate: '',
    estCompletionDate: '',
    actualCompletionDate: '',
    parts: [],
  },

  feeBill: {
    billDate: '',
    professionalFee: 1800,
    riFee: 0,
    travelExpenses: 250,
    travelNote: 'Pune city travel',
    distanceKm: 15,
    ratePerKm: 10,
    tollCharges: 0,
    tollNote: '',
    photosCount: 12,
    photoRate: 10,
    postalCharges: 50,
    haltageCharges: 0,
    includeGST: true,
    advanceReceipt: '',
    cashReceived: '',
    salvageValue: 0,
    lessExcess: 0,
    compulsoryExcess: 1000,
    voluntaryExcess: 0,
    feePaid: false,
  },

  valuationDetails: {
    inspectionDate: '',
    inspectionPlace: '',
    odometer: '',
    chassis: '',
    engineTransmission: '',
    suspension: '',
    seats: '',
    electricals: '',
    batteryMake: '',
    batteryCondition: '',
    tyreCount: '',
    stepneyCount: '',
    tyreMake: '',
    tyreCondition: '',
    glassCondition: '',
    panelRows: [],
    toName: '',
    toAddress: '',
    isInsurable: true,
    coverRecommendation: '',
    documentVerificationNote: '',
    enclosures: '',
    remarks: '',
  },

  billCheck: {
    billNo: '',
    billDate: '',
    billTotal: 0,
  },

  documentVerification: {
    rc: { status: 'Verified', detail: 'RC verified — details match' },
    dl: { status: 'Verified', detail: 'DL valid, class LMV, non-transport valid till 2034' },
    permit: { status: 'N/A', detail: 'Private vehicle — no permit required' },
    loadChallan: { status: 'N/A', detail: '' },
    fitness: { status: 'N/A', detail: 'Private vehicle — no fitness required' },
    fireReport: { status: 'N/A', detail: 'No fire involved' },
    fir: { status: 'Available', detail: 'FIR No. FIR/CHT/2026/0447 obtained' },
  },

  photos: [],
  photoLayout: 6,
  photoLandscape: false,

  extractedData: {},
  gDriveFolderId: null,
  telemetrySent: false,
  reportPreamble: 'The insured vehicle was surveyed at Shree Motors Workshop, Baner, Pune on 10.06.2026. Damage is consistent with the reported accident. Documents were verified and found in order. Assessment has been carried out as per IRDAI guidelines and the terms of the policy.',
};
